### ISSUE TITLE
test v0.1.3

### ISSUE THREAD

**Issue by fthome** [FredThx/FCALC#4]
log : mode info vs debug
bug : 1-0-/ : supp de la stack
ajouter info bulle sur les items stack + détail calcul moins moche

**Comment by FredThx** [comment]
47824b177fcb47c6bb09cc377704f186b80cf7dc
c60be7d020489df5ffaf624d5446390e2dfd8df8
e8d19c3d31c491bdf390a093f4049f5cc1d9d199
